site_name: scmRTOS
site_url: https://scmrtos.github.io/
#use_directory_urls: false

theme:
    name: readthedocs
    max_width: 2000
    navigation_depth: 5
    font: false
    features:
        - content.code.copy
        - content.code.annotate
    #name: windmill

extra_css: 
    - extra.css


nav:
    - Введение:
        - Вместо предисловия             : index.md 
        - Обзор операционной системы     : src/overview.md
    
    - Компоненты:
        - Ядро                           : src/kernel.md
        - Процессы                       : src/processes.md
        - Межпроцессное взаимодействие   : src/ipcs.md
        - Порты                          : src/ports.md

    - Приложения:
        - Отладка                        : src/debug.md
        - Профилировка процессов         : src/profiler.md
        - 'Пример: очередь заданий'      : src/example-job-queue.md
        - Термины и сокращения           : src/glossary.md

extra_javascript:
    - js/mathjax.js
    - js/mathjax/tex-mml-chtml.js
    - js/wavedrom.min.js
    - js/wavedrom_loader.js
    - js/wavedrom.unpkg.js
    - js/wavedrom_skin_default.js


markdown_extensions:
    - toc:
        permalink: "🔗"
        baselevel: 1
    - pymdownx.arithmatex:
       generic: true    
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
    - search:
        lang: ru

    - glightbox
    #- markdownwavedrom
